# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bms-anomaly-detection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acrbbk8s.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1d5bf204de6e402488ee8efb3a1e586a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c335257ae99548c08bd3a63fb2bd4e81 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acrbbk8s.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1d5bf204de6e402488ee8efb3a1e586a }}/dep-bms-ad:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bms-anomaly-detection'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_03d7d8d364374485aba0d6aa6646a972 }}
        images: 'acrbbk8s.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1d5bf204de6e402488ee8efb3a1e586a }}/dep-bms-ad:${{ github.sha }}'